 // made by ayush
 const quotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The best way to predict the future is to invent it. - Alan Kay",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Happiness is not something readymade. It comes from your own actions. - Dalai Lama",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "In the middle of difficulty lies opportunity. - Albert Einstein",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Quality is not an act, it is a habit. - Aristotle",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "The best preparation for tomorrow is doing your best today. - H. Jackson Brown, Jr.",
    "Change your thoughts and you change your world. - Norman Vincent Peale",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "The secret of getting ahead is getting started. - Mark Twain",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The best way to predict the future is to invent it. - Alan Kay",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Happiness is not something readymade. It comes from your own actions. - Dalai Lama",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "In the middle of difficulty lies opportunity. - Albert Einstein",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Quality is not an act, it is a habit. - Aristotle",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "The best preparation for tomorrow is doing your best today. - H. Jackson Brown, Jr.",
    "Change your thoughts and you change your world. - Norman Vincent Peale",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "The secret of getting ahead is getting started. - Mark Twain",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The best way to predict the future is to invent it. - Alan Kay",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Happiness is not something readymade. It comes from your own actions. - Dalai Lama",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "In the middle of difficulty lies opportunity. - Albert Einstein",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "Don't watch the clock; do what it does. Keep going. - Sam",
        ];
  
  
        function generateQuote() {
            const randomNumber = Math.floor(Math.random() * quotes.length);
            const quoteElement = document.getElementById('quote');
            quoteElement.textContent = quotes[randomNumber];
          }
 